/*
 * Auto-generated by the ESP32-C3 Audio Mixer Configurator.
 * Generated: 2026-09-30 20:53:15
 * DO NOT hand-edit this file -- regenerate it from the desktop app instead.
 *
 * Hardware: ESP32-C3 SuperMini, 5 analog slider(s), 2 push button(s),
 * 128x64 monochrome I2C OLED (SSD1306-compatible) driven via U8g2.
 * LED strip: WS2812/NeoPixel enabled.
 *
 * Serial protocol: one deej-compatible line per update, e.g.
 *   0|512|1023|300|900
 * Button shortcut actions are emitted as tagged lines, e.g.
 *   @shortcut:F13
 *   @shortcut:CTRL+ALT+M
 * These tagged lines require a desktop shortcut bridge to become real
 * OS keyboard events -- this firmware is a serial device only, it does
 * NOT act as a USB HID keyboard.
 *
 * No secrets or external credentials are stored on this device.
 */

#include <Wire.h>
#include <U8g2lib.h>
#include <Preferences.h>
#include <Adafruit_NeoPixel.h>


// ---------------------------------------------------------------------
// Configuration (generated)
// ---------------------------------------------------------------------
#define NUM_CHANNELS 5
#define NUM_BUTTONS  2

#define OLED_SDA_PIN 8
#define OLED_SCL_PIN 9
#define OLED_I2C_ADDR 0x3C
  #define LED_STRIP_ENABLED true
  #define LED_DATA_PIN 5
  #define LED_COUNT 2
  #define LED_BRIGHTNESS 64
  #define LED_LOW_R 0
  #define LED_LOW_G 255
  #define LED_LOW_B 0
  #define LED_HIGH_R 255
  #define LED_HIGH_G 0
  #define LED_HIGH_B 0
  

#define SERIAL_BAUD 115200
#define UPDATE_INTERVAL_MS 30
#define DEBOUNCE_MS 30
#define CALIBRATION_MS 4000

const int SLIDER_PINS[NUM_CHANNELS] = {0, 1, 2, 3, 4};
const int BUTTON_PINS[NUM_BUTTONS]  = {10, 20};
const int BUTTON_TRIGGER_ON_PRESS[NUM_BUTTONS] = {1, 1}; // 1 = fire on press, 0 = fire on release

int ADC_MIN[NUM_CHANNELS] = {0, 0, 0, 0, 0};
int ADC_MAX[NUM_CHANNELS] = {4095, 4095, 4095, 4095, 4095};
const bool CH_INVERT[NUM_CHANNELS]  = {false, false, false, false, false};
const bool CH_VISIBLE[NUM_CHANNELS] = {true, true, true, true, true};
const int  CH_STYLE[NUM_CHANNELS]   = {0, 0, 0, 0, 0}; // 0=Bar 1=Number 2=Hidden
const char* CH_LABEL[NUM_CHANNELS]  = {"CH1", "CH2", "CH3", "CH4", "CH5"};

const float SMOOTHING_ALPHA = 0.2f; // weight kept from the previous sample (0=none .. <1=heavy)
int channelOutput[NUM_CHANNELS];

const char* OLED_TITLE  = "Audio Mixer";
const char* OLED_FOOTER = "deej";
const bool SHOW_TITLE   = true;
const bool SHOW_FOOTER  = true;
const bool SHOW_STATUS  = true;
const bool SHOW_LABELS  = true;
const bool SHOW_MASTER  = false;
const bool SHOW_MUTE_INDICATOR = true;
const bool SHOW_PEAK_INDICATOR = false;
const bool SHOW_NUMERIC_VALUES = true;

// ---------------------------------------------------------------------
// Globals
// ---------------------------------------------------------------------
U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);
Preferences prefs;
Adafruit_NeoPixel ledStrip(LED_COUNT, LED_DATA_PIN, NEO_GRB + NEO_KHZ800);

float smoothed[NUM_CHANNELS];
bool channelMuted[NUM_CHANNELS];
bool allMuted = false;
int muteCursor = 0;
bool screenOn = true;

bool calibrating = false;
unsigned long calibrationEndAt = 0;
int calMin[NUM_CHANNELS];
int calMax[NUM_CHANNELS];

int lastRawState[NUM_BUTTONS];
int stableState[NUM_BUTTONS];
unsigned long lastEdgeAt[NUM_BUTTONS];

unsigned long lastUpdateAt = 0;

// ---------------------------------------------------------------------
// Calibration persistence (NVS via Preferences, no external credentials)
// ---------------------------------------------------------------------
void loadCalibration() {
  prefs.begin("mixer", true);
  for (int i = 0; i < NUM_CHANNELS; i++) {
    char keyMin[8]; char keyMax[8];
    snprintf(keyMin, sizeof(keyMin), "min%d", i);
    snprintf(keyMax, sizeof(keyMax), "max%d", i);
    if (prefs.isKey(keyMin)) ADC_MIN[i] = prefs.getInt(keyMin, ADC_MIN[i]);
    if (prefs.isKey(keyMax)) ADC_MAX[i] = prefs.getInt(keyMax, ADC_MAX[i]);
  }
  prefs.end();
}

void saveCalibration() {
  prefs.begin("mixer", false);
  for (int i = 0; i < NUM_CHANNELS; i++) {
    char keyMin[8]; char keyMax[8];
    snprintf(keyMin, sizeof(keyMin), "min%d", i);
    snprintf(keyMax, sizeof(keyMax), "max%d", i);
    prefs.putInt(keyMin, ADC_MIN[i]);
    prefs.putInt(keyMax, ADC_MAX[i]);
  }
  prefs.end();
}

void startCalibration() {
  calibrating = true;
  calibrationEndAt = millis() + CALIBRATION_MS;
  for (int i = 0; i < NUM_CHANNELS; i++) {
    calMin[i] = 4095;
    calMax[i] = 0;
  }
}

void updateCalibration(int idx, int raw) {
  if (raw < calMin[idx]) calMin[idx] = raw;
  if (raw > calMax[idx]) calMax[idx] = raw;
}

void finishCalibrationIfDue() {
  if (!calibrating) return;
  if ((long)(millis() - calibrationEndAt) < 0) return;
  calibrating = false;
  bool changed = false;
  for (int i = 0; i < NUM_CHANNELS; i++) {
    if (calMax[i] > calMin[i] + 32) { // ignore noise-only sweeps
      ADC_MIN[i] = calMin[i];
      ADC_MAX[i] = calMax[i];
      changed = true;
    }
  }
  if (changed) saveCalibration();
}

// ---------------------------------------------------------------------
// Button actions
// ---------------------------------------------------------------------
void handleButtonAction(int idx) {
  if (idx == 0) {
    screenOn = !screenOn;
    u8g2.setPowerSave(screenOn ? 0 : 1);
    return;
  }
  if (idx == 1) {
    allMuted = !allMuted;
    return;
  }
}

void pollButtons() {
  unsigned long now = millis();
  for (int i = 0; i < NUM_BUTTONS; i++) {
    int raw = digitalRead(BUTTON_PINS[i]); // INPUT_PULLUP: LOW = pressed

    if (raw != lastRawState[i]) {
      lastEdgeAt[i] = now;
      lastRawState[i] = raw;
    }

    if ((now - lastEdgeAt[i]) > DEBOUNCE_MS && raw != stableState[i]) {
      stableState[i] = raw;
      bool pressed = (stableState[i] == LOW);
      bool fireOnPress = (BUTTON_TRIGGER_ON_PRESS[i] == 1);
      if ((pressed && fireOnPress) || (!pressed && !fireOnPress)) {
        handleButtonAction(i);
      }
    }
  }
}

// ---------------------------------------------------------------------
// Sliders / serial output
// ---------------------------------------------------------------------
int mapChannel(int idx, float rawSmoothed) {
  long v = map((long)rawSmoothed, ADC_MIN[idx], ADC_MAX[idx], 0, 1023);
  v = constrain(v, 0L, 1023L);
  if (CH_INVERT[idx]) v = 1023 - v;
  if (allMuted || channelMuted[idx]) v = 0;
  return (int)v;
}

void pollSlidersAndReport() {
  String line = "";
  for (int i = 0; i < NUM_CHANNELS; i++) {
    int raw = analogRead(SLIDER_PINS[i]); // 12-bit: 0-4095
    smoothed[i] = (smoothed[i] * SMOOTHING_ALPHA) + ((float)raw * (1.0f - SMOOTHING_ALPHA));

    if (calibrating) updateCalibration(i, raw);

    int outVal = mapChannel(i, smoothed[i]);
    channelOutput[i] = outVal;
    line += String(outVal);
    if (i < NUM_CHANNELS - 1) line += "|";
  }
  Serial.println(line);
    updateLedStrip();
}

uint32_t colorWheel(uint8_t position) {
  position = 255 - position;
  if (position < 85) return ledStrip.Color(255 - position * 3, 0, position * 3);
  if (position < 170) {
    position -= 85;
    return ledStrip.Color(0, position * 3, 255 - position * 3);
  }
  position -= 170;
  return ledStrip.Color(position * 3, 255 - position * 3, 0);
}

void setLedLevel(int index, int level) {
  level = constrain(level, 0, 1023);
  uint8_t red = (uint8_t)(LED_LOW_R + (LED_HIGH_R - LED_LOW_R) * level / 1023);
  uint8_t green = (uint8_t)(LED_LOW_G + (LED_HIGH_G - LED_LOW_G) * level / 1023);
  uint8_t blue = (uint8_t)(LED_LOW_B + (LED_HIGH_B - LED_LOW_B) * level / 1023);
  ledStrip.setPixelColor(index, ledStrip.Color(red, green, blue));
}

void updateLedStrip() {
  for (int i = 0; i < LED_COUNT; i++) {
    uint8_t position = (uint8_t)((i * 256 / LED_COUNT + millis() / 8) & 255);
    ledStrip.setPixelColor(i, colorWheel(position));
  }
  ledStrip.show();
}

// ---------------------------------------------------------------------
// OLED rendering
// ---------------------------------------------------------------------
bool channelShown(int i) {
  if (i >= 5) return false;
  return CH_VISIBLE[i] && CH_STYLE[i] != 2;
}

void drawChrome() {
  if (SHOW_TITLE && strlen(OLED_TITLE) > 0) {
    u8g2.setFont(u8g2_font_6x10_tf);
    u8g2.drawStr(2, 9, OLED_TITLE);
    u8g2.drawHLine(0, 11, 128);
  }
  if (SHOW_FOOTER && strlen(OLED_FOOTER) > 0) {
    u8g2.setFont(u8g2_font_5x7_tf);
    u8g2.drawStr(2, 63, OLED_FOOTER);
  }
  if (SHOW_STATUS) {
    u8g2.setFont(u8g2_font_5x7_tf);
    if (calibrating) {
      u8g2.drawStr(80, 9, "CAL");
    } else if (SHOW_MUTE_INDICATOR && allMuted) {
      u8g2.drawStr(90, 9, "MUTE");
    }
  }
}

void drawLayout() {
  drawChrome();
  int top = SHOW_TITLE ? 14 : 2;
  int bottom = SHOW_FOOTER ? 60 : 63;
  int labelH = SHOW_LABELS ? 8 : 0;
  int barTop = top;
  int barBottom = bottom - labelH;
  int barMaxH = barBottom - barTop;
  if (barMaxH < 4) barMaxH = 4;

  bool drawMaster = false;
  int cols = 0;
  for (int i = 0; i < NUM_CHANNELS; i++) if (channelShown(i)) cols++;
  if (drawMaster) cols += 1;
  if (cols == 0) cols = 1;
  int colW = 126 / cols;
  int x = 2;

  u8g2.setFont(u8g2_font_5x7_tf);

  if (drawMaster) {
    long sum = 0; int n = 0;
    for (int i = 0; i < NUM_CHANNELS; i++) {
      if (!channelShown(i)) continue;
      sum += mapChannel(i, smoothed[i]);
      n++;
    }
    int avg = (n > 0) ? (int)(sum / n) : 0;
    int barH = (avg * barMaxH) / 1023;
    u8g2.drawFrame(x, barBottom - barMaxH, colW - 3, barMaxH);
    u8g2.drawBox(x, barBottom - barH, colW - 3, barH);
    if (SHOW_LABELS) u8g2.drawStr(x, bottom, "MSTR");
    x += colW;
  }

  for (int i = 0; i < NUM_CHANNELS; i++) {
    if (!channelShown(i)) continue;
    int v = mapChannel(i, smoothed[i]);
    int barH = (v * barMaxH) / 1023;
    bool muted = channelMuted[i] || allMuted;

    u8g2.drawFrame(x, barBottom - barMaxH, colW - 3, barMaxH);
    if (!muted) {
      u8g2.drawBox(x, barBottom - barH, colW - 3, barH);
    }
    if (SHOW_PEAK_INDICATOR && v > 950 && !muted) {
      u8g2.drawBox(x, barBottom - barMaxH, colW - 3, 2);
    }
    if (SHOW_LABELS) {
      u8g2.drawStr(x, bottom, CH_LABEL[i]);
    }
    if (SHOW_NUMERIC_VALUES && CH_STYLE[i] != 2) {
      char buf[8];
      snprintf(buf, sizeof(buf), "%d", v);
      u8g2.setFont(u8g2_font_4x6_tf);
      u8g2.drawStr(x, barBottom - barMaxH - 1, buf);
      u8g2.setFont(u8g2_font_5x7_tf);
    }
    x += colW;
  }
}


void drawScreen() {
  u8g2.clearBuffer();
  drawLayout();
  u8g2.sendBuffer();
}

// ---------------------------------------------------------------------
// Arduino entry points
// ---------------------------------------------------------------------
void setup() {
  Serial.begin(SERIAL_BAUD);

  for (int i = 0; i < NUM_CHANNELS; i++) {
    smoothed[i] = (float)((ADC_MIN[i] + ADC_MAX[i]) / 2);
    channelMuted[i] = false;
  }

  for (int i = 0; i < NUM_BUTTONS; i++) {
    pinMode(BUTTON_PINS[i], INPUT_PULLUP);
    lastRawState[i] = digitalRead(BUTTON_PINS[i]);
    stableState[i] = lastRawState[i];
    lastEdgeAt[i] = millis();
  }

  analogReadResolution(12);

  loadCalibration();

  Wire.begin(OLED_SDA_PIN, OLED_SCL_PIN);
  u8g2.begin();
  u8g2.setI2CAddress(OLED_I2C_ADDR << 1);
  u8g2.setPowerSave(0);
  ledStrip.begin();
  ledStrip.setBrightness(LED_BRIGHTNESS);
  ledStrip.show();
}

void loop() {
  unsigned long now = millis();

  pollButtons();
  finishCalibrationIfDue();

  if (now - lastUpdateAt >= (unsigned long)UPDATE_INTERVAL_MS) {
    lastUpdateAt = now;
    pollSlidersAndReport();
    if (screenOn) drawScreen();
  }
}
